Django/advence_section/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view()),
    path(r"basic_app/", include("basic_app.urls", namespace="basic_app"))
]

Django/advence_section/advcbv/basic_app/urls.py
from basic_app import views
from django.urls import path

app_name = "basic_app"

urlpatterns = [
    path(r"", views.SchoolListView.as_view(), name="list"),
    path(r"<int:pk>", views.SchoolDetailView.as_view(), name="detail"),
    path(r'create/', views.SchoolCreateView.as_view(), name="create"),
    path(r'update/<int:pk>', views.SchoolUpdateView.as_view(), name="update"),
    path(r'delete/<int:pk>', views.SchoolDeleteView.as_view(), name="delete"),
]

Django/advence_section/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={"pk": self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name="students", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Django/advence_section/advcbv/basic_app/views.py
from django.views.generic import (ListView, DeleteView,
                                  UpdateView, TemplateView,
                                  CreateView, DetailView)
from django.urls import reverse_lazy

from . import models


class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    model = models.School
    context_object_name = "schools"


class SchoolDetailView(DetailView):
    model = models.School
    template_name = "basic_app/school_detail.html"
    context_object_name = "school_detail"


class SchoolCreateView(CreateView):
    model = models.School
    fields = ("name", "principal", "location")


class SchoolUpdateView(UpdateView):
    fields = ("name", "principal")
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

Django/advence_section/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>Base</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
{%block body_block%}
{%endblock%}
</div>
</body>
</html>

Django/advence_section/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{%extends "basic_app/basic_app_base.html"%}
{%block body_block%}
<h1>Delete {{school.name}}?</h1>
<form method="post">
    {%csrf_token%}
    <input type="submit" class="btn btn-danger" value="Detele">
    <a class="btn btn-danger" href="{%url 'basic_app:detail' pk=school.pk%}">Cancel</a>
</form>

{%endblock%}

Django/advence_section/advcbv/basic_app/templates/basic_app/school_detail.html
{%extends 'basic_app/basic_app_base.html'%}
{%block body_block %}
<div class="p-5 md-4 bg-body-tertiary rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">
            Welcome to the School Detail page
        </h1>
        <h2>School details</h2>
        <p>Name: {{school_detail.name}}</p>
        <p>Principal: {{school_detail.principal}}</p>
        <p>Location: {{school_detail.location}}</p>
        <h3>Students:</h3>
        {% for student in school_detail.students.all %}
        <p>{{student.name}} whi is {{student.age}} years old.</p>
        {% endfor %}
    </div>
</div>
<div class="container">
    <p><a class="btn btn-warning" href="{%url 'basic_app:update' pk=school_detail.pk%}">Update</a></p>
    <p><a class="btn btn-danger" href="{%url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
</div>
{%endblock%}

Django/advence_section/advcbv/basic_app/templates/basic_app/school_form.html
{%extends "basic_app/basic_app_base.html"%}

{%block body_block %}
<h1>
    {%if not form.instance.pk %}
    Create School
    {%else%}
    Update School
    {%endif%}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary btn-lg" type="submit" value="Submit"></input>

</form>
{%endblock%}

Django/advence_section/advcbv/basic_app/templates/basic_app/school_list.html
{%extends 'basic_app/basic_app_base.html'%}

{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>
<ol>
    {%for school in schools%}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {%endfor%}
</ol>

{%endblock%}

Django/advence_section/advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>Base</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
{%block body_block%}
{%endblock%}
</div>
</body>
</html>

Django/advence_section/advcbv/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Home page</h1>
<!--        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>-->
<!--        <button class="btn btn-primary btn-lg" type="button">Example button</button>-->
      </div>
    </div>
{%endblock%}