Django/Django_level_four/learning_templetes/basicapp/urls.py
from basicapp import views
from django.urls import path

#Template tagging
app_name = "basicapp"

urlpatterns = [
    path("relative/", views.relative, name="relative"),
    path("other/", views.other, name="other"),
]

Django/Django_level_four/learning_templetes/learning_templetes/urls.py
from basicapp import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(r"", views.index, name="index"),
    path("basicapp/", include("basicapp.urls")),
    path("base/", views.base, name = "base"),

]

Django/Django_level_four/learning_templetes/basicapp/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    context_dıct={'text':'hello world', 'number':100}
    return render(request, "basicapp/index.html", context=context_dıct)

def other(request):
    return render(request, "basicapp/other.html")

def relative(request):
    return render(request,"basicapp/relative_url_templates.html")

def base(request):
    return render(request,"basicapp/base.html")

Django/Django_level_four/learning_templetes/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BASE</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-brand nav-link" href="{% url 'index' %}">BRAND</a></li>
            <li class="nav-item"><a class="nav-item nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
            <li class="nav-item"><a class="nav-item nav-link" href="{% url 'basicapp:other'%}">OTHER</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    <!--    somthing-->
    {% endblock %}
    </div>
</body>
</html>

Django/Django_level_four/learning_templetes/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>WELCOME TO INDEX</h1>
<h1>this is index.html</h1>
<h1>{{ text | cut:"world" }}</h1>
<h1>{{ number| add:"100" }}</h1>
{% endblock %}

Django/Django_level_four/learning_templetes/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>WELCOME TO OTHER</h1>
<h2>This is an example of template inheritance</h2>
{% endblock %}

Django/Django_level_four/learning_templetes/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Welcome to url templates</h1>
<a href="{% url 'basic_app:other' %}">The other page</a>
<a href="{% url 'admin:index' %}">LINK to ADMIN</a>
<a href="{% url 'index' %}">index</a>
</body>
</html>